# Generated by Django 4.2.6 on 2023-12-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text_comment',
        ),
    ]
